//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.Sudoku.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCS.Sudoku.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert&apos;s Sudoku Solver.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Puzzle does not have {0} rows..
        /// </summary>
        public static string ErrorPuzzleRows_rows {
            get {
                return ResourceManager.GetString("ErrorPuzzleRows_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Row {0} does not have {1} digits..
        /// </summary>
        public static string ErrorRowDigits_row_digits {
            get {
                return ResourceManager.GetString("ErrorRowDigits_row_digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Row {0} does not have digits only..
        /// </summary>
        public static string ErrorRowNonDigits_row {
            get {
                return ResourceManager.GetString("ErrorRowNonDigits_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string FileMessageLabel {
            get {
                return ResourceManager.GetString("FileMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string FileReadText {
            get {
                return ResourceManager.GetString("FileReadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        public static string MessageFileName_name {
            get {
                return ResourceManager.GetString("MessageFileName_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string SolveMessageLabel {
            get {
                return ResourceManager.GetString("SolveMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        public static string SolveText {
            get {
                return ResourceManager.GetString("SolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed in {0} seconds..
        /// </summary>
        public static string StatusFailed_seconds {
            get {
                return ResourceManager.GetString("StatusFailed_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start..
        /// </summary>
        public static string StatusPrepared {
            get {
                return ResourceManager.GetString("StatusPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on it....
        /// </summary>
        public static string StatusStarted {
            get {
                return ResourceManager.GetString("StatusStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded in {0} seconds..
        /// </summary>
        public static string StatusSucceeded_seconds {
            get {
                return ResourceManager.GetString("StatusSucceeded_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for data....
        /// </summary>
        public static string StatusUnprepared {
            get {
                return ResourceManager.GetString("StatusUnprepared", resourceCulture);
            }
        }
    }
}
